version: "3"
services:
  authors:
    build: ./authors
    expose:
      - "50001"
    links:
      - mongodb    
  books:
    build: ./books
    expose:
      - "50002"
    links:
      - mongodb
    environment: 
      - AUTHORS_GRPC_CONNECTION_URL=authors:50051
  bff:
    build: ./bff
    ports:
      - "8093:8080"
    depends_on:
      - authors
      - books
    links:
      - authors
      - books
    environment: 
      - AUTHORS_GRPC_CONNECTION_URL=authors:50051
      - BOOKS_GRPC_CONNECTION_URL=books:50052
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    links:
      - authors
      - books
      - bff
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:      